# Generated by Django 5.0.6 on 2024-06-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_first_name_profile_last_name'),
    ]

    operations = [
    ]
